### ISSUE TITLE
`acknowledge-existing-violations` omits colon after `noqa`, which ignores all errors, not specific errors

### ISSUE THREAD

**Issue by bkeryan** [ni/python-styleguide#125]
`ni-python-styleguide acknowledge-existing-violations` adds `noqa` comments without a colon, like this one:
```
    def GetMetadata(  # noqa N802: function name 'GetMetadata' should be lowercase (auto-generated noqa)
        self, request: v1_measurement_service_pb2.GetMetadataRequest, context: grpc.ServicerContext
    ) -> v1_measurement_service_pb2.GetMetadataResponse:
```

https://www.alpharithms.com/noqa-python-501210/ says

> Multiple codes can be given, separated by a comma. The noqa token is case insensitive, the colon before the list of codes is required otherwise the part after noqa is ignored

I noticed this because I added type annotations and `ni-python-styleguide fix` did not wrap the extremely long line.

Related: https://github.com/ni/measurementlink-python/issues/250

**Comment by mshafer-NI** [comment]
Fix released in 0.4.1

**Comment by bkeryan** [comment]
Unfortunately, `acknowledge-existing-violations` doesn't leave the code in a state where `lint` passes.

For example, `acknowledge-existing-violations` adds this `noqa`:
```
    def RegisterService(self, request):  # noqa: N802 - function name 'RegisterService' should be lowercase (auto-generated noqa)
 ```

`lint` says the `noqa` makes `black` want to reformat the line: 
```
.\tests\utilities\fake_discovery_service.py:14:25: BLK100 Black would make changes.
```
 Previously, the blanket `noqa` prevented any reformatting.

`fix` runs `black`, rewriting it as:
```
    def RegisterService(
        self, request
    ):  # noqa: N802 - function name 'RegisterService' should be lowercase (auto-generated noqa)
```

`lint` says the noqa is on the wrong line:
```
.\tests\utilities\fake_discovery_service.py:14:10: N802 function name 'RegisterService' should be lowercase
```

`acknowledge-existing-violations` rewrites it as:
```
    def RegisterService(  # noqa: N802 - function name 'RegisterService' should be lowercase (auto-generated noqa)
        self, request
    ):  # noqa: N802 - function name 'RegisterService' should be lowercase (auto-generated noqa)
```

Now you have two `noqa`s.

**Comment by mshafer-NI** [comment]
> Unfortunately, `acknowledge-existing-violations` doesn't leave the code in a state where `lint` passes.
> 
> ...
> ```
>     def RegisterService(  # noqa: N802 - function name 'RegisterService' should be lowercase (auto-generated noqa)
>         self, request
>     ):  # noqa: N802 - function name 'RegisterService' should be lowercase (auto-generated noqa)
> ```
> 
> Now you have two `noqa`s.

This is what the `fix --aggresssive` option addresses. It will iteratively acknowledge issues, run black (if changes were made) remove existing statements and go again.

0.4.1 was released on Friday with a patch on how the comments are generated. Please try `fix --aggressive` with that version.
